"""update_2

Revision ID: 55bbb5f0a367
Revises: b27cb9c5d800
Create Date: 2025-08-08 12:22:29.502182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55bbb5f0a367'
down_revision: Union[str, Sequence[str], None] = 'b27cb9c5d800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'match', ['id_fixture'])
    op.create_unique_constraint(None, 'match', ['id_events'])
    op.add_column('statistics', sa.Column('statistics_team_id', sa.Integer(), nullable=True))
    op.alter_column('statistics', 'score_ht',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('statistics', 'score_ft',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('statistics', 'fouls',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('statistics', 'corners',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('statistics', 'offside',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('statistics', 'bass_possession',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('statistics', 'yellow_cards',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('statistics', 'red_cards',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('statistics', 'goal_keeper',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistics', 'goal_keeper',
               existing_type=sa.Integer(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('statistics', 'red_cards',
               existing_type=sa.Integer(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('statistics', 'yellow_cards',
               existing_type=sa.Integer(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('statistics', 'bass_possession',
               existing_type=sa.Integer(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('statistics', 'offside',
               existing_type=sa.Integer(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('statistics', 'corners',
               existing_type=sa.Integer(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('statistics', 'fouls',
               existing_type=sa.Integer(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('statistics', 'score_ft',
               existing_type=sa.Integer(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('statistics', 'score_ht',
               existing_type=sa.Integer(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('statistics', 'statistics_team_id')
    op.drop_constraint(None, 'match', type_='unique')
    op.drop_constraint(None, 'match', type_='unique')
    # ### end Alembic commands ###
