"""prima creazione tabelle

Revision ID: 6db9b72a39ab
Revises: 
Create Date: 2025-08-05 11:14:31.019926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db9b72a39ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id_match_fk', sa.String(length=36), nullable=False),
    sa.Column('id_events', sa.String(length=32), nullable=True),
    sa.Column('id_fixture', sa.Integer(), nullable=True),
    sa.Column('name_home', sa.String(), nullable=True),
    sa.Column('id_team_home', sa.Integer(), nullable=True),
    sa.Column('name_away', sa.String(), nullable=True),
    sa.Column('id_team_away', sa.Integer(), nullable=True),
    sa.Column('date_match', sa.String(), nullable=True),
    sa.Column('sport_key', sa.String(), nullable=True),
    sa.Column('title_league', sa.String(), nullable=True),
    sa.Column('round', sa.String(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_match_fk')
    )
    op.create_table('statistics',
    sa.Column('id_statistics_fk', sa.String(length=36), nullable=False),
    sa.Column('id_match', sa.String(length=36), nullable=True),
    sa.Column('score_ht', sa.JSON(), nullable=True),
    sa.Column('score_ft', sa.JSON(), nullable=True),
    sa.Column('shots', sa.JSON(), nullable=True),
    sa.Column('fouls', sa.JSON(), nullable=True),
    sa.Column('corners', sa.JSON(), nullable=True),
    sa.Column('offside', sa.JSON(), nullable=True),
    sa.Column('bass_possession', sa.JSON(), nullable=True),
    sa.Column('yellow_cards', sa.JSON(), nullable=True),
    sa.Column('red_cards', sa.JSON(), nullable=True),
    sa.Column('goal_keeper', sa.JSON(), nullable=True),
    sa.Column('passes', sa.JSON(), nullable=True),
    sa.Column('form', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_match'], ['match.id_match_fk'], ),
    sa.PrimaryKeyConstraint('id_statistics_fk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    op.drop_table('match')
    # ### end Alembic commands ###
