"""referee

Revision ID: b7f92099ff79
Revises: 6db9b72a39ab
Create Date: 2025-08-05 17:49:37.731124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f92099ff79'
down_revision: Union[str, Sequence[str], None] = '6db9b72a39ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('referee', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'referee')
    # ### end Alembic commands ###
