"""update

Revision ID: fa096a1ea63b
Revises: b7f92099ff79
Create Date: 2025-08-05 17:56:22.187023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa096a1ea63b'
down_revision: Union[str, Sequence[str], None] = 'b7f92099ff79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('for_', sa.JSON(), nullable=True))
    op.add_column('statistics', sa.Column('against', sa.JSON(), nullable=True))
    op.add_column('statistics', sa.Column('preview_matches', sa.JSON(), nullable=True))
    op.add_column('statistics', sa.Column('comparison', sa.JSON(), nullable=True))
    op.add_column('statistics', sa.Column('generic_statistics', sa.JSON(), nullable=True))
    op.add_column('statistics', sa.Column('predict', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics', 'predict')
    op.drop_column('statistics', 'generic_statistics')
    op.drop_column('statistics', 'comparison')
    op.drop_column('statistics', 'preview_matches')
    op.drop_column('statistics', 'against')
    op.drop_column('statistics', 'for_')
    # ### end Alembic commands ###
