"""generate

Revision ID: 87c01cea446f
Revises: fa096a1ea63b
Create Date: 2025-08-06 11:09:26.849063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c01cea446f'
down_revision: Union[str, Sequence[str], None] = 'fa096a1ea63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odds',
    sa.Column('id_odds_fk', sa.String(length=36), nullable=False),
    sa.Column('id_match', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['id_match'], ['match.id_match_fk'], ),
    sa.PrimaryKeyConstraint('id_odds_fk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odds')
    # ### end Alembic commands ###
