"""generate

Revision ID: b27cb9c5d800
Revises: 87c01cea446f
Create Date: 2025-08-06 12:20:11.801584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27cb9c5d800'
down_revision: Union[str, Sequence[str], None] = '87c01cea446f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('id_alternate_events', sa.String(length=32), nullable=True))
    op.add_column('match', sa.Column('date_alternate_match', sa.String(), nullable=True))
    op.add_column('odds', sa.Column('odds_from', sa.String(), nullable=True))
    op.add_column('odds', sa.Column('h2h', sa.JSON(), nullable=True))
    op.add_column('odds', sa.Column('under_over_1_5', sa.JSON(), nullable=True))
    op.add_column('odds', sa.Column('under_over_2_5', sa.JSON(), nullable=True))
    op.add_column('odds', sa.Column('under_over_3_5', sa.JSON(), nullable=True))
    op.add_column('odds', sa.Column('under_over_4_5', sa.JSON(), nullable=True))
    op.add_column('odds', sa.Column('under_over_home_away', sa.JSON(), nullable=True))
    op.add_column('odds', sa.Column('goal_no_goal', sa.JSON(), nullable=True))
    op.add_column('odds', sa.Column('corners', sa.JSON(), nullable=True))
    op.add_column('odds', sa.Column('cards', sa.JSON(), nullable=True))
    op.add_column('odds', sa.Column('dc', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odds', 'dc')
    op.drop_column('odds', 'cards')
    op.drop_column('odds', 'corners')
    op.drop_column('odds', 'goal_no_goal')
    op.drop_column('odds', 'under_over_home_away')
    op.drop_column('odds', 'under_over_4_5')
    op.drop_column('odds', 'under_over_3_5')
    op.drop_column('odds', 'under_over_2_5')
    op.drop_column('odds', 'under_over_1_5')
    op.drop_column('odds', 'h2h')
    op.drop_column('odds', 'odds_from')
    op.drop_column('match', 'date_alternate_match')
    op.drop_column('match', 'id_alternate_events')
    # ### end Alembic commands ###
